### ISSUE TITLE
火币现货/v1/order/openOrders接口参数变化

### ISSUE THREAD

**Issue by noranhe** [vn-crypto/vnpy_huobi#2]
huobi_sopt_gateway的query_order函数对应的/v1/order/openOrders接口，现要求参数account-id和symbol都是必填参数（默认值为NA）。
![53013adb6c777a838524ffcc552cf7b](https://user-images.githubusercontent.com/63988546/129996850-735a1250-3754-494e-819a-29c7634f4344.png)

**Comment by vn-crypto** [comment]
u r welcome to send a PR for this.
